CREATE TABLE ISSUESLISTS
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100)
);

CREATE TABLE ISSUES
(
    ID SERIAL PRIMARY KEY,
    ISSUESLIST_ID BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (ISSUESLIST_ID) REFERENCES ISSUESLISTS(ID),
    SUMMARY VARCHAR(100),
    DESCRIPTION VARCHAR(500),
    USER_ID_ASSIGNEDTO BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (USER_ID_ASSIGNEDTO) REFERENCES USERS(ID)

);
INSERT INTO ISSUESLISTS (NAME)
VALUES ("ToDo");
INSERT INTO ISSUESLISTS (NAME)
VALUES ("In progress");
INSERT INTO ISSUESLISTS (NAME)
VALUES ("Done");
COMMIT ;

INSERT INTO ISSUES (SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO, ISSUESLIST_ID)
VALUES ("SUMMARY1","DESCRIPTION1",1,2);
INSERT INTO ISSUES (SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO, ISSUESLIST_ID)
VALUES ("SUMMARY2","DESCRIPTION2",1,3);
INSERT INTO ISSUES (SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO, ISSUESLIST_ID)
VALUES ("SUMMARY1","DESCRIPTION1",2,2);
INSERT INTO ISSUES (SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO, ISSUESLIST_ID)
VALUES ("SUMMARY2","DESCRIPTION2",2,3);
INSERT INTO ISSUES (SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO, ISSUESLIST_ID)
VALUES ("SUMMARY1","DESCRIPTION1",3,3);
INSERT INTO ISSUES (SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO, ISSUESLIST_ID)
VALUES ("SUMMARY2","DESCRIPTION3",3,3);
COMMIT ;

update posts set BODY = "123" where ID = 6;




