select * from POSTS;
INSERT INTO POSTS (USER_ID, BODY)
VALUES (3, "NEW POST");
INSERT INTO POSTS (USER_ID, BODY)
VALUES (3, "NEW POST 2");
INSERT INTO POSTS (USER_ID, BODY)
VALUES (4, "NEW POST 3");
COMMIT;
select * from POSTS;
UPDATE POSTS
SET BODY = "To delete"
WHERE ID = 10;
COMMIT;
select * from POSTS;
UPDATE POSTS
SET BODY = "To delete"
WHERE ID = 9;
COMMIT;
select * from POSTS;
DELETE FROM POSTS
WHERE ID = 10;
COMMIT;
select * from POSTS;